// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX1hLnujZGrhdSYAdqZ74Ac1P6o-MvcOI',
    appId: '1:242612700344:web:450ff7e6aa45b0341fe04d',
    messagingSenderId: '242612700344',
    projectId: 'smartroombookingbiher',
    authDomain: 'smartroombookingbiher.firebaseapp.com',
    storageBucket: 'smartroombookingbiher.firebasestorage.app',
    measurementId: 'G-7410LH1KCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd9SEIlUa40jIhvLM-JtOOkfezfvpWB6g',
    appId: '1:242612700344:android:4e39a44ae3bd2dc01fe04d',
    messagingSenderId: '242612700344',
    projectId: 'smartroombookingbiher',
    storageBucket: 'smartroombookingbiher.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFQyX1Ow0uw4b8QXk5UUCOlRT2MpT63M',
    appId: '1:242612700344:ios:a9c74a0e1e1a53e01fe04d',
    messagingSenderId: '242612700344',
    projectId: 'smartroombookingbiher',
    storageBucket: 'smartroombookingbiher.firebasestorage.app',
    iosBundleId: 'com.smartroombooking.biher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFQyX1Ow0uw4b8QXk5UUCOlRT2MpT63M',
    appId: '1:242612700344:ios:40c3005767e845071fe04d',
    messagingSenderId: '242612700344',
    projectId: 'smartroombookingbiher',
    storageBucket: 'smartroombookingbiher.firebasestorage.app',
    iosBundleId: 'com.example.smartroombooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX1hLnujZGrhdSYAdqZ74Ac1P6o-MvcOI',
    appId: '1:242612700344:web:9c59304e4061e6f51fe04d',
    messagingSenderId: '242612700344',
    projectId: 'smartroombookingbiher',
    authDomain: 'smartroombookingbiher.firebaseapp.com',
    storageBucket: 'smartroombookingbiher.firebasestorage.app',
    measurementId: 'G-QV5G7L8GXV',
  );
}
